export enum MessageLevel {
    Status,
    Advisory,
    Caution,
    Warning,
}

export enum CasMessage {
    L_ENG_FIRE,
    R_ENG_FIRE,
    L_ENG_FIRE_DET_FAIL,
    R_ENG_FIRE_DET_FAIL,
    L_R_ENG_BTL_FAIL,
    L_ENG_BTL_FAIL,
    R_ENG_BTL_FAIL,
    ENG_BTL_1_LO,
    ENG_BTL_2_LO,
    L_ENG_BTL_FAULT,
    R_ENG_BTL_FAULT,
    APU_FIRE,
    APU_FIRE_DET_FAIL,
    APU_BTL_FAIL,
    APU_BTL_LO,
    FWD_CARGO_FIRE,
    AFT_CARGO_FIRE,
    CARGO_BTL_FAIL,
    FWD_CARGO_BTL_FAIL,
    AFT_CARGO_BTL_FAIL,
    CARGO_BTL_LO,
    FWD_CARGO_SMOKE_FAIL,
    AFT_CARGO_SMOKE_FAIL,
    EQUIP_BAY_SMOKE,
    EQUIP_BAY_SMOKE_FAIL,
    LAV_SMOKE,
    LAV_SMOKE_FAIL,
    MLG_BAY_OVHT,
    MLG_BAY_OVHT_DET_FAIL,
    FIRE_SYSTEM_FAIL,
    FIRE_SYSTEM_FAULT,
    GEAR,
    GEAR_AURAL_CNCL,
    NOSE_STEER_FAIL,
    NOSE_STEER_FAULT,
    NOSE_STEER_MISALIGN,
    GEAR_DISAGREE,
    GEAR_FAIL,
    GEAR_FAULT,
    WOW_FAIL,
    WOW_FAULT,
    ALTN_GEAR_DN_ADV,
    PEDAL_STEER_DISC,
    NOSE_STEER_OFF,
    ALTN_GEAR_DN_STAT,
    CONFIG_RUDDER_TRIM,
    CONFIG_STAB_TRIM,
    CONFIG_SPOILER,
    CONFIG_SIDESTICK,
    L_SIDESTICK,
    R_SIDESTICK,
    FLT_CTRL_DIRECT_ADS,
    FLT_CTRL_DIRECT_IRS,
    FLT_CTRL_DIRECT_WARN,
    FLT_CTRL_DIRECT_CAUT,
    RUDDER_DEGRADED,
    RUDDER_FAIL,
    L_ELEVATOR_FAIL_CAUT,
    R_ELEVATOR_FAIL_CAUT,
    L_ELEVATOR_FAIL_WARN,
    R_ELEVATOR_FAIL_WARN,
    STAB_TRIM_FAIL,
    STAB_DEGRADED,
    ALPHA_LIMIT,
    GND_LIFT_DUMP_FAIL,
    SPOILER_DEGRADED,
    GND_SPOILER_FAIL,
    SPOILER_FAIL,
    AILERON_FAIL,
    SPOILER_DPLY,
    SPOILER_LEVER_FAIL,
    STEEP_NOT_AVAILABLE,
    ADS_DEGRADED,
    SPOILER_MISMATCH,
    L_PITCH_TRIM_SW_FAIL,
    R_PITCH_TRIM_SW_FAIL,
    YAW_AUTHORITY,
    PITCH_AUTHORITY,
    ROLL_AUTHORITY,
    PFCC_1_OFF,
    PFCC_1_FAIL,
    PFCC_2_OFF,
    PFCC_2_FAIL,
    PFCC_3_OFF,
    PFCC_3_FAIL,
    FLT_CTRL_FAULT,
    FLT_CTRL_TEST_REQ,
    FLT_CTRL_IN_TEST,
    SPOILER_DPLY_ADV,
    EQUIP_BAY_OVHT,
    EQUIP_BAY_COOL_FAIL,
    EXHAUST_AIR_ON,
    EXHAUST_AIR_VLV_ONLY,
    INLET_AIR_OFF,
    L_AIR_SYS_CTLR_FAIL,
    R_AIR_SYS_CTLR_FAIL,
    AIR_SYS_ESS_CTLR_FAIL,
    L_PACK_FAIL,
    R_PACK_FAIL,
    L_PACK_OVHT,
    R_PACK_OVHT,
    L_PACK_OFF,
    R_PACK_OFF,
    TRIM_AIR_FAIL,
    TRIM_AIR_OFF,
    RAM_AIR_FAIL,
    RAM_AIR_OPEN,
    PACK_FLOW_HI,
    MAN_TEMP_ON,
    ADS_1_FAIL,
    ADS_2_FAIL,
    ADS_3_FAIL,
    ADS_4_FAIL,
    DUAL_ADS_FAIL,
    L_PFD_ISI_SAME_ADS,
    R_PFD_ISI_SAME_ADS,
    ADS_1_PROBE_HEAT_FAIL,
    ADS_2_PROBE_HEAT_FAIL,
    ADS_3_PROBE_HEAT_FAIL,
    ADS_4_PROBE_HEAT_FAIL,
    ADS_ISI_PROBE_HEAT,
    ADS_1_SLIPCOMP_FAIL,
    ADS_2_SLIPCOMP_FAIL,
    ADS_3_SLIPCOMP_FAIL,
    ADS_4_SLIPCOMP_FAIL,
    ADS_ISI_SLIPCOMP_FAIL,
    ADS_FAULT,
    ADS_PROBE_HEAT_GND_ON,
    ADS_1_DEGRADED,
    ADS_2_DEGRADED,
    ADS_3_DEGRADED,
    ADS_4_DEGRADED,
    ADS_MAINT_MODE_ACTIVE,
    HI_LOAD_MONITOR_FAIL,
    HEALTH_MGMT_FAULT,
    HI_LOAD_EVENT,
    APU_OVERSPEED,
    APU,
    APU_BLEED_FAIL,
    APU_DOOR_OPEN,
    APU_OIL_LO_TEMP,
    APU_IN_START,
    APU_ON,
    APU_SHUTDOWN,
    APU_FAULT,
    APU_OIL_LO_QTY,
    DISPLAY_REV_MISCONFIG,
    IPC_1_FAIL,
    IPC_2_FAIL,
    IPC_3_FAIL,
    IPC_4_FAIL,
    RAD_ALT_1_FAIL,
    RAD_ALT_2_FAIL,
    RAD_ALT_3_FAIL,
    RAD_ALT_FAIL,
    AUTO_FLIGHT_FAULT,
    AT_RETARD_INHIBIT,
    FD_MODE_CHANGE,
    CONFIG_AP,
    EMER_DESCENT_WARN,
    EMER_DESCENT_CAUT,
    CONFIG_AT,
    CONFIG_THRUST_LEVER,
    L_ENG_AT_OFF,
    R_ENG_AT_OFF,
    FMS_OEI_PERF_ACTIVE,
    APPR1_NOT_AVAIL,
    APPR2_NOT_AVAIL,
    LAND2_NOT_AVAIL,
    LAND3_NOT_AVAIL,
    WXR_ON,
    L_R_RADIO_TUNING_FAIL,
    L_CTP_TUNING_FAIL,
    R_CTP_TUNING_FAIL,
    AURAL_FAIL,
    AURAL_WARN_INHIB,
    AUDIO_PNL_1_FAIL,
    AUDIO_PNL_2_FAIL,
    SELCAL,
    VHF_COM_121_5_ENABLE,
    DATALINK_FAIL,
    DATALINK_STATUS,
    SATCOM_FAIL,
    SATCOM_NO_SIGNAL,
    SATCOM_DATA_FAIL,
    SATCOM_VOICE_FAIL,
    SAT_VOICE_NO_SIGNAL,
    VHF3_IN_VOICE,
    DSPL_TUNE_INHIB,
    CURSOR_INHIB,
    CTP_OVERRIDE,
    EFIS_COMPARATOR_FAIL,
    EFIS_MISCOMPARE,
    ENG_DSPL_MISCOMPARE,
    HUD_FAIL,
    L_HUD_FAIL,
    R_HUD_FAIL,
    LVTO_NOT_AVAIL,
    L_LVTO_NOT_AVAIL,
    R_LVTO_NOT_AVAIL,
    CAS_MISCOMPARE,
    DMC_1A_FAIL,
    DMC_1B_FAIL,
    DMC_2A_FAIL,
    DMC_2B_FAIL,
    AT_FAIL,
    FD_FAIL,
    DMC_1_FAIL,
    DMC_2_FAIL,
    TCAS_FAIL,
    TCAS_OFF,
    TAWS_FAIL,
    GROUND_PROX_FAIL,
    WINDSHEAR_FAIL,
    TAWS_MAP_FAIL,
    TAWS_TERRAIN_FAIL,
    TAWS_GS_CNCL,
    TAWS_FLAP_INHIB,
    TAWS_TERR_INHIB,
    TAWS_GEAR_INHIB,
    WXR_FAIL,
    WXR_CTRL_FAULT,
    WXR_FAULT,
    WXR_TURB_FAULT,
    WXR_AUTO_FAULT,
    WXR_PWS_FAIL,
    XPDR_1_FAIL,
    XPDR_2_FAIL,
    ADSB_OUT_FAIL,
    ADSB_1_OUT_FAIL,
    ADSB_2_OUT_FAIL,
    SMS_RUNWAY_INHIB,
    SMS_RUNWAY_N_A,
    SMS_FAIL,
    FMS_1_FAIL,
    FMS_2_FAIL,
    FMS_FUEL,
    APPROACH_NOT_AVAIL,
    FMS_POSITION,
    LPV_NOT_AVAIL,
    UNABLE_RNP,
    GNSS_NOT_AVAILABLE,
    FMS_PERF_DEP_VSPEEDS,
    FMS_PERF_DEP_CONFIG,
    AC_MAINTENANCE_SW,
    AVIONIC_FAULT,
    AVIONIC_FAN_FAULT,
    L_BLEED_LEAK,
    R_BLEED_LEAK,
    WING_A_ICE_LEAK,
    APU_BLEED_LEAK,
    L_PACK_LEAK,
    R_PACK_LEAK,
    TRIM_AIR_LEAK,
    LEAK_DET_FAIL,
    L_BLEED_FAIL,
    R_BLEED_FAIL,
    L_BLEED_OVHT,
    R_BLEED_OVHT,
    L_BLEED_OFF,
    R_BLEED_OFF,
    ENG_BLEED_MISCONFIG,
    XBLEED_FAIL,
    XBLEED_MAN_CLSD,
    XBLEED_MAN_OPEN,
    APU_BLEED_OFF,
    CONFIG_BRAKE,
    BRAKE_OVHT,
    BRAKE_ON,
    NORM_BRAKE_FAIL,
    ALTN_BRAKE_FAIL,
    BRAKE_FAIL,
    PARK_BRAKE_FAIL,
    PLT_BRAKE_PEDAL_FAIL,
    CPLT_BRAKE_PEDAL_FAIL,
    L_BRAKE_FAIL,
    R_BRAKE_FAIL,
    AUTOBRAKE_FAIL,
    BRAKE_TEMP,
    L_BRAKE_DEGRADED,
    R_BRAKE_DEGRADED,
    BRAKE_FAULT,
    PARK_BRAKE_ON,
    ALTN_BRAKE_ON,
    AUTOBRAKE_RTO,
    AUTOBRAKE_HI,
    AUTOBRAKE_MED,
    AUTOBRAKE_LO,
    CARGO_DOOR,
    CABIN_COM_FAULT,
    SEAT_BELTS,
    NO_PED,
    CABIN_DIFF_PRESS,
    CABIN_ALT_WARN,
    CABIN_ALT_CAUT,
    AUTO_PRESS_FAIL,
    EMER_DEPRESS_ON,
    DITCHING_ON,
    DITCHING_MISCONFIG,
    CABIN_PRESS_MAN,
    CABIN_ALT_LEVEL_HI,
    LDG_ELEV_MISCONFIG,
    CVR_FAIL,
    FDR_FAIL,
    PILOT_EVENT,
    FDR_ACCEL_FAIL,
    RECIRC_AIR_FAIL,
    RECIRC_AIR_OFF,
    FWD_CARGO_HEAT_FAIL,
    FWD_CARGO_LO_TEMP,
    FWD_CARGO_AIR_OFF,
    AFT_CARGO_AIR_OFF,
    EMER_PWR_ONLY,
    BATT_EMER_PWR_ON,
    BATT_1_OVERTEMP,
    BATT_2_OVERTEMP,
    APU_GEN_FAIL,
    BATT_DISCHARGING,
    BATT_1_FAIL,
    BATT_2_FAIL,
    L_GEN_FAIL,
    L_GEN_OIL,
    R_GEN_FAIL,
    R_GEN_OIL,
    AC_BUS_1,
    AC_BUS_2,
    AC_ESS_BUS,
    DC_BUS_1,
    DC_BUS_2,
    DC_ESS_BUS_1,
    DC_ESS_BUS_2,
    DC_ESS_BUS_3,
    DC_EMER_BUS,
    RAT_GEN_FAIL,
    TRU_FAULT,
    CB_TRIP,
    ELECTRICAL_FAULT,
    LOAD_SHED,
    BATT_CHARGER_FAULT,
    RAT_DPLY_ADV,
    RAT_GEN_ON,
    EXT_PWR_AVAIL,
    EXT_PWR_IN_USE,
    ELEC_BUS_ISOL_MAIN,
    ELEC_BUS_ISOL_ESS,
    CABIN_PWR_OFF,
    L_GEN_OFF,
    L_GEN_DISC,
    R_GEN_OFF,
    R_GEN_DISC,
    APU_GEN_OFF,
    BATT_PWR_CONFIG,
    BATT_1_OFF,
    BATT_2_OFF,
    ELT_ON,
    ELT_DT_ON,
    ELT_DT_FAIL,
    ELT_DT_FAULT,
    EQUIP_BAY_DOOR,
    L_ENG_SHUTDOWN,
    R_ENG_SHUTDOWN,
    L_ENG_FAIL,
    R_ENG_FAIL,
    DUAL_ENG_FAIL,
    L_ENG_EXCEEDANCE,
    R_ENG_EXCEEDANCE,
    L_THROTTLE_FAIL,
    R_THROTTLE_FAIL,
    ENG_SETTING_MISMATCH,
    L_ENGINE_FAULT,
    R_ENGINE_FAULT,
    ENG_VIBRATION,
    L_ENG_START_ABORT,
    R_ENG_START_ABORT,
    L_ENG_STARTER_FAIL_ON,
    R_ENG_STARTER_FAIL_ON,
    ENG_CONT_IGNITION_ON,
    L_REVERSER_FAIL,
    R_REVERSER_FAIL,
    L_REVERSER_UNLOCK,
    R_REVERSER_UNLOCK,
    L_REVERSER_INHIBIT,
    R_REVERSER_INHIBIT,
    THROTTLE_IN_REVERSE,
    L_COWL_A_ICE_FAIL,
    R_COWL_A_ICE_FAIL,
    L_COWL_A_ICE_ON,
    R_COWL_A_ICE_ON,
    L_R_COWL_A_ICE_ON,
    COWL_A_ICE_ON,
    L_COWL_A_ICE_FAIL_ON,
    R_COWL_A_ICE_FAIL_ON,
    L_COWL_A_ICE_OFF,
    R_COWL_A_ICE_OFF,
    L_R_COWL_A_ICE_OFF,
    L_ENG_OIL_PRESS,
    R_ENG_OIL_PRESS,
    L_ENG_OIL_LO_QTY,
    R_ENG_OIL_LO_QTY,
    APR_DISARMED,
    L_ENG_OPER_DEGRADED,
    R_ENG_OPER_DEGRADED,
    ENG_OIL_LO_TEMP,
    L_ENG_FUEL_FILTER,
    R_ENG_FUEL_FILTER,
    L_R_ENG_FUEL_FILTER,
    L_ENG_OIL_FILTER,
    R_ENG_OIL_FILTER,
    L_ENG_NACELLE_OVHT,
    R_ENG_NACELLE_OVHT,
    L_ENG_PCE_DOOR_OPEN,
    R_ENG_PCE_DOOR_OPEN,
    L_FUEL_FLOW_DEGRADED,
    R_FUEL_FLOW_DEGRADED,
    L_ENG_STARTER_OVHT,
    R_ENG_STARTER_OVHT,
    ENG_START_DELAY,
    CKPT_DOOR_LOCK_FAIL,
    CKPT_DOOR_OPEN,
    CKPT_DOOR_LOCK_OFF,
    CKPT_DOOR_EMER_ACCESS,
    FUEL_INERTING_FAULT,
    L_FUEL_LO_QTY,
    R_FUEL_LO_QTY,
    FUEL_TANK_LO_TEMP,
    FUEL_TANK_HI_TEMP,
    FUEL_IMBALANCE,
    L_ENG_FUEL_SOV_FAIL,
    R_ENG_FUEL_SOV_FAIL,
    APU_FUEL_SOV_FAIL,
    L_ENG_FUEL_LO_PRESS,
    R_ENG_FUEL_LO_PRESS,
    FUEL_CTR_XFR_FAIL,
    FUEL_MAN_XFR_FAIL,
    FUEL_COLLECTOR_LO_LVL,
    FUEL_LEAK_SUSPECT,
    FUEL_MAN_XFR_COMPLETE,
    FUEL_GRAV_XFR_FAIL,
    FUEL_CTR_XFR_FAULT,
    L_BOOST_PUMP_FAIL,
    R_BOOST_PUMP_FAIL,
    L_FUEL_EJECTOR_FAIL,
    R_FUEL_EJECTOR_FAIL,
    FUEL_COMPUTER_FAIL,
    FUEL_FAULT,
    L_ENG_FUEL_SOV_CLSD,
    R_ENG_FUEL_SOV_CLSD,
    APU_FUEL_SOV_CLSD,
    L_BOOST_PUMP_ON,
    R_BOOST_PUMP_ON,
    L_BOOST_PUMP_OFF,
    R_BOOST_PUMP_OFF,
    FUEL_MAN_XFR_TO_L,
    FUEL_MAN_XFR_TO_R,
    FUEL_MAN_XFR_TO_CTR,
    FUEL_GRAV_XFR_ON,
    FUEL_XFR_CTR_READY,
    FUEL_ACT_XFR_FAIL,
    FUEL_ACT_XFR_DEGRADED,
    FUEL_ACT_ISOLATED,
    FUEL_ACT_SOV_OPEN,
    FUEL_ACT_SOV_CLOSED,
    FUEL_ACT_XFR_OFF,
    FUEL_ACT_XFR_BACKUP,
    FUEL_ACT_FAULT,
    FUEL_QUANTITY_FAULT,
    CONFIG_FLAP,
    SLAT_SKEW,
    SLAT_FLAP_LEVER_FAIL,
    FLAP_FAIL,
    SLAT_FAIL,
    SLAT_AND_FLAP_FAIL,
    SLAT_SLOW_CAUT,
    FLAP_SLOW_CAUT,
    SLAT_SLOW_ADV,
    FLAP_SLOW_ADV,
    SLAT_FAULT,
    FLAP_FAULT,
    ALTN_FLAP_DPLY,
    HYD_1_HI_TEMP,
    HYD_2_HI_TEMP,
    HYD_3_HI_TEMP,
    HYD_1_LO_PRESS,
    HYD_2_LO_PRESS,
    HYD_3_LO_PRESS,
    HYD_1_2_LO_PRESS,
    HYD_2_3_LO_PRESS,
    HYD_1_3_LO_PRESS,
    HYD_1_SOV_FAIL,
    HYD_2_SOV_FAIL,
    HYD_EDP_1A_FAIL,
    HYD_PTU_FAIL,
    HYD_EDP_2A_FAIL,
    HYD_PUMP_2B_FAIL,
    HYD_PUMP_3A_FAIL,
    HYD_PUMP_3B_FAIL,
    HYD_RAT_PUMP_FAIL,
    HYD_1_LO_QTY,
    HYD_2_LO_QTY,
    HYD_3_LO_QTY,
    HYD_1_SOV_CLSD_ADV,
    HYD_2_SOV_CLSD_ADV,
    HYDRAULIC_FAULT,
    HYD_1_SOV_CLSD_STAT,
    HYD_2_SOV_CLSD_STAT,
    HYD_PTU_OFF,
    HYD_PTU_ON,
    HYD_PUMP_2B_OFF,
    HYD_PUMP_2B_ON,
    HYD_PUMP_3A_OFF,
    HYD_PUMP_3A_ON,
    HYD_PUMP_3B_OFF,
    HYD_PUMP_3B_ON,
    AIR_SYSTEM_FAULT,
    LEAK_DET_FAULT,
    PACK_FAULT,
    EQUIP_BAY_COOL_FAULT,
    WING_A_ICE_FAULT,
    PRESSURIZATION_FAULT,
    KU_BAND_ON,
    CTRL_PANEL_FAULT,
    L_ICE_DET_FAIL,
    R_ICE_DET_FAIL,
    ICE_CAUT,
    ICE_ADV,
    EMER_LTS_ON,
    EMER_LTS_OFF,
    IRS_1_FAIL,
    IRS_2_FAIL,
    IRS_3_FAIL,
    IRS_SAME_SOURCE,
    IRS_SET_HEADING,
    IRS_1_POWER_FAULT,
    IRS_2_POWER_FAULT,
    IRS_3_POWER_FAULT,
    CREW_OXY_LO_PRESS,
    PAX_OXY_DPLY,
    OVERWING_DOOR,
    WING_SLIDE,
    FWD_DOOR,
    AFT_DOOR,
    DOOR_OPEN,
    DOOR_FAULT,
    FWD_SLIDE,
    AFT_SLIDE,
    DOOR_SLIDE_DISARMED_CAUT,
    DOOR_SLIDE_DISARMED_ADV,
    DOOR_SLIDE_FAULT,
    TIRE_PRESS_FAULT,
    TIRE_LO_PRESS,
    NOSE_TIRE_LO_PRESS,
    L_WING_A_ICE_OVHT,
    R_WING_A_ICE_OVHT,
    WING_A_ICE_MISCONFIG,
    L_WING_A_ICE_LO_HEAT,
    R_WING_A_ICE_LO_HEAT,
    L_WING_A_ICE_FAIL,
    R_WING_A_ICE_FAIL,
    WING_A_ICE_FAIL,
    WING_A_ICE_ON_CAUT,
    WING_A_ICE_OFF,
    WING_A_ICE_ON_STAT,
    L_WSHLD_HEAT_FAIL_ON,
    R_WSHLD_HEAT_FAIL_ON,
    L_SIDE_WDW_HT_FAIL_ON,
    R_SIDE_WDW_HT_FAIL_ON,
    L_WSHLD_HEAT_OFF,
    R_WSHLD_HEAT_OFF,
    L_SIDE_WDW_HEAT_OFF,
    R_SIDE_WDW_HEAT_OFF,
    L_WSHLD_HEAT_FAIL,
    R_WSHLD_HEAT_FAIL,
    L_SIDE_WDW_HEAT_FAIL,
    R_SIDE_WDW_HEAT_FAIL,
}

export const CAS_MESSAGE_TEXT: { [key in CasMessage]: [MessageLevel, string] } = {
    [CasMessage.L_ENG_FIRE]: [MessageLevel.Warning, "L ENG FIRE"],
    [CasMessage.R_ENG_FIRE]: [MessageLevel.Warning, "R ENG FIRE"],
    [CasMessage.L_ENG_FIRE_DET_FAIL]: [MessageLevel.Caution, "L ENG FIRE DET FAIL"],
    [CasMessage.R_ENG_FIRE_DET_FAIL]: [MessageLevel.Caution, "R ENG FIRE DET FAIL"],
    [CasMessage.L_R_ENG_BTL_FAIL]: [MessageLevel.Caution, "L-R ENG BTL FAIL"],
    [CasMessage.L_ENG_BTL_FAIL]: [MessageLevel.Caution, "L ENG BTL FAIL"],
    [CasMessage.R_ENG_BTL_FAIL]: [MessageLevel.Caution, "R ENG BTL FAIL"],
    [CasMessage.ENG_BTL_1_LO]: [MessageLevel.Advisory, "ENG BTL 1 LO"],
    [CasMessage.ENG_BTL_2_LO]: [MessageLevel.Advisory, "ENG BTL 2 LO"],
    [CasMessage.L_ENG_BTL_FAULT]: [MessageLevel.Advisory, "L ENG BTL FAULT"],
    [CasMessage.R_ENG_BTL_FAULT]: [MessageLevel.Advisory, "R ENG BTL FAULT"],
    [CasMessage.APU_FIRE]: [MessageLevel.Warning, "APU FIRE"],
    [CasMessage.APU_FIRE_DET_FAIL]: [MessageLevel.Caution, "APU FIRE DET FAIL"],
    [CasMessage.APU_BTL_FAIL]: [MessageLevel.Caution, "APU BTL FAIL"],
    [CasMessage.APU_BTL_LO]: [MessageLevel.Advisory, "APU BTL LO"],
    [CasMessage.FWD_CARGO_FIRE]: [MessageLevel.Warning, "FWD CARGO FIRE"],
    [CasMessage.AFT_CARGO_FIRE]: [MessageLevel.Warning, "AFT CARGO FIRE"],
    [CasMessage.CARGO_BTL_FAIL]: [MessageLevel.Caution, "CARGO BTL FAIL"],
    [CasMessage.FWD_CARGO_BTL_FAIL]: [MessageLevel.Caution, "FWD CARGO BTL FAIL"],
    [CasMessage.AFT_CARGO_BTL_FAIL]: [MessageLevel.Caution, "AFT CARGO BTL FAIL"],
    [CasMessage.CARGO_BTL_LO]: [MessageLevel.Advisory, "CARGO BTL LO"],
    [CasMessage.FWD_CARGO_SMOKE_FAIL]: [MessageLevel.Caution, "FWD CARGO SMOKE FAIL"],
    [CasMessage.AFT_CARGO_SMOKE_FAIL]: [MessageLevel.Caution, "AFT CARGO SMOKE FAIL"],
    [CasMessage.EQUIP_BAY_SMOKE]: [MessageLevel.Warning, "EQUIP BAY SMOKE"],
    [CasMessage.EQUIP_BAY_SMOKE_FAIL]: [MessageLevel.Caution, "EQUIP BAY SMOKE FAIL"],
    [CasMessage.LAV_SMOKE]: [MessageLevel.Warning, "LAV SMOKE"],
    [CasMessage.LAV_SMOKE_FAIL]: [MessageLevel.Caution, "LAV SMOKE FAIL"],
    [CasMessage.MLG_BAY_OVHT]: [MessageLevel.Warning, "MLG BAY OVHT"],
    [CasMessage.MLG_BAY_OVHT_DET_FAIL]: [MessageLevel.Caution, "MLG BAY OVHT DET FAIL"],
    [CasMessage.FIRE_SYSTEM_FAIL]: [MessageLevel.Caution, "FIRE SYSTEM FAIL"],
    [CasMessage.FIRE_SYSTEM_FAULT]: [MessageLevel.Advisory, "FIRE SYSTEM FAULT"],
    [CasMessage.GEAR]: [MessageLevel.Warning, "GEAR"],
    [CasMessage.GEAR_AURAL_CNCL]: [MessageLevel.Status, "GEAR AURAL CNCL"],
    [CasMessage.NOSE_STEER_FAIL]: [MessageLevel.Caution, "NOSE STEER FAIL"],
    [CasMessage.NOSE_STEER_FAULT]: [MessageLevel.Advisory, "NOSE STEER FAULT"],
    [CasMessage.NOSE_STEER_MISALIGN]: [MessageLevel.Caution, "NOSE STEER MISALIGN"],
    [CasMessage.GEAR_DISAGREE]: [MessageLevel.Caution, "GEAR DISAGREE"],
    [CasMessage.GEAR_FAIL]: [MessageLevel.Caution, "GEAR FAIL"],
    [CasMessage.GEAR_FAULT]: [MessageLevel.Advisory, "GEAR FAULT"],
    [CasMessage.WOW_FAIL]: [MessageLevel.Caution, "WOW FAIL"],
    [CasMessage.WOW_FAULT]: [MessageLevel.Advisory, "WOW FAULT"],
    [CasMessage.ALTN_GEAR_DN_ADV]: [MessageLevel.Advisory, "ALTN GEAR DN"],
    [CasMessage.PEDAL_STEER_DISC]: [MessageLevel.Status, "PEDAL STEER DISC"],
    [CasMessage.NOSE_STEER_OFF]: [MessageLevel.Status, "NOSE STEER OFF"],
    [CasMessage.ALTN_GEAR_DN_STAT]: [MessageLevel.Status, "ALTN GEAR DN"],
    [CasMessage.CONFIG_RUDDER_TRIM]: [MessageLevel.Warning, "CONFIG RUDDER TRIM"],
    [CasMessage.CONFIG_STAB_TRIM]: [MessageLevel.Warning, "CONFIG STAB TRIM"],
    [CasMessage.CONFIG_SPOILER]: [MessageLevel.Warning, "CONFIG SPOILER"],
    [CasMessage.CONFIG_SIDESTICK]: [MessageLevel.Warning, "CONFIG SIDESTICK"],
    [CasMessage.L_SIDESTICK]: [MessageLevel.Caution, "L SIDESTICK"],
    [CasMessage.R_SIDESTICK]: [MessageLevel.Caution, "R SIDESTICK"],
    [CasMessage.FLT_CTRL_DIRECT_ADS]: [MessageLevel.Caution, "FLT CTRL DIRECT ADS"],
    [CasMessage.FLT_CTRL_DIRECT_IRS]: [MessageLevel.Caution, "FLT CTRL DIRECT IRS"],
    [CasMessage.FLT_CTRL_DIRECT_WARN]: [MessageLevel.Warning, "FLT CTRL DIRECT"],
    [CasMessage.FLT_CTRL_DIRECT_CAUT]: [MessageLevel.Caution, "FLT CTRL DIRECT"],
    [CasMessage.RUDDER_DEGRADED]: [MessageLevel.Caution, "RUDDER DEGRADED"],
    [CasMessage.RUDDER_FAIL]: [MessageLevel.Warning, "RUDDER FAIL"],
    [CasMessage.L_ELEVATOR_FAIL_CAUT]: [MessageLevel.Caution, "L ELEVATOR FAIL"],
    [CasMessage.R_ELEVATOR_FAIL_CAUT]: [MessageLevel.Caution, "R ELEVATOR FAIL"],
    [CasMessage.L_ELEVATOR_FAIL_WARN]: [MessageLevel.Warning, "L ELEVATOR FAIL"],
    [CasMessage.R_ELEVATOR_FAIL_WARN]: [MessageLevel.Warning, "R ELEVATOR FAIL"],
    [CasMessage.STAB_TRIM_FAIL]: [MessageLevel.Caution, "STAB TRIM FAIL"],
    [CasMessage.STAB_DEGRADED]: [MessageLevel.Caution, "STAB DEGRADED"],
    [CasMessage.ALPHA_LIMIT]: [MessageLevel.Caution, "ALPHA LIMIT"],
    [CasMessage.GND_LIFT_DUMP_FAIL]: [MessageLevel.Caution, "GND LIFT DUMP FAIL"],
    [CasMessage.SPOILER_DEGRADED]: [MessageLevel.Caution, "SPOILER DEGRADED"],
    [CasMessage.GND_SPOILER_FAIL]: [MessageLevel.Caution, "GND SPOILER FAIL"],
    [CasMessage.SPOILER_FAIL]: [MessageLevel.Caution, "SPOILER FAIL"],
    [CasMessage.AILERON_FAIL]: [MessageLevel.Caution, "AILERON FAIL"],
    [CasMessage.SPOILER_DPLY]: [MessageLevel.Caution, "SPOILER DPLY"],
    [CasMessage.SPOILER_LEVER_FAIL]: [MessageLevel.Caution, "SPOILER LEVER FAIL"],
    [CasMessage.STEEP_NOT_AVAILABLE]: [MessageLevel.Caution, "STEEP NOT AVAIL"],
    [CasMessage.ADS_DEGRADED]: [MessageLevel.Caution, "ADS DEGRADED"],
    [CasMessage.SPOILER_MISMATCH]: [MessageLevel.Advisory, "SPOILER MISMATCH"],
    [CasMessage.L_PITCH_TRIM_SW_FAIL]: [MessageLevel.Advisory, "L PITCH TRIM SW FAIL"],
    [CasMessage.R_PITCH_TRIM_SW_FAIL]: [MessageLevel.Advisory, "R PITCH TRIM SW FAIL"],
    [CasMessage.YAW_AUTHORITY]: [MessageLevel.Caution, "YAW AUTHORITY"],
    [CasMessage.PITCH_AUTHORITY]: [MessageLevel.Caution, "PITCH AUTHORITY"],
    [CasMessage.ROLL_AUTHORITY]: [MessageLevel.Caution, "ROLL AUTHORITY"],
    [CasMessage.PFCC_1_OFF]: [MessageLevel.Status, "PFCC 1 OFF"],
    [CasMessage.PFCC_1_FAIL]: [MessageLevel.Advisory, "PFCC 1 FAIL"],
    [CasMessage.PFCC_2_OFF]: [MessageLevel.Status, "PFCC 2 OFF"],
    [CasMessage.PFCC_2_FAIL]: [MessageLevel.Advisory, "PFCC 2 FAIL"],
    [CasMessage.PFCC_3_OFF]: [MessageLevel.Status, "PFCC 3 OFF"],
    [CasMessage.PFCC_3_FAIL]: [MessageLevel.Advisory, "PFCC 3 FAIL"],
    [CasMessage.FLT_CTRL_FAULT]: [MessageLevel.Advisory, "FLT CTRL FAULT"],
    [CasMessage.FLT_CTRL_TEST_REQ]: [MessageLevel.Advisory, "FLT CTRL TEST REQ"],
    [CasMessage.FLT_CTRL_IN_TEST]: [MessageLevel.Advisory, "FLT CTRL IN TEST"],
    [CasMessage.SPOILER_DPLY_ADV]: [MessageLevel.Advisory, "SPOILER DPLY"],
    [CasMessage.EQUIP_BAY_OVHT]: [MessageLevel.Warning, "EQUIP BAY OVHT"],
    [CasMessage.EQUIP_BAY_COOL_FAIL]: [MessageLevel.Caution, "EQUIP BAY COOL FAIL"],
    [CasMessage.EXHAUST_AIR_ON]: [MessageLevel.Status, "EXHAUST AIR ON"],
    [CasMessage.EXHAUST_AIR_VLV_ONLY]: [MessageLevel.Status, "EXHAUST AIR VLV ONLY"],
    [CasMessage.INLET_AIR_OFF]: [MessageLevel.Status, "INLET AIR OFF"],
    [CasMessage.L_AIR_SYS_CTLR_FAIL]: [MessageLevel.Caution, "L AIR SYS CTLR FAIL"],
    [CasMessage.R_AIR_SYS_CTLR_FAIL]: [MessageLevel.Caution, "R AIR SYS CTLR FAIL"],
    [CasMessage.AIR_SYS_ESS_CTLR_FAIL]: [MessageLevel.Caution, "AIR SYS ESS CTLR FAIL"],
    [CasMessage.L_PACK_FAIL]: [MessageLevel.Caution, "L PACK FAIL"],
    [CasMessage.R_PACK_FAIL]: [MessageLevel.Caution, "R PACK FAIL"],
    [CasMessage.L_PACK_OVHT]: [MessageLevel.Caution, "L PACK OVHT"],
    [CasMessage.R_PACK_OVHT]: [MessageLevel.Caution, "R PACK OVHT"],
    [CasMessage.L_PACK_OFF]: [MessageLevel.Status, "L PACK OFF"],
    [CasMessage.R_PACK_OFF]: [MessageLevel.Status, "R PACK OFF"],
    [CasMessage.TRIM_AIR_FAIL]: [MessageLevel.Caution, "TRIM AIR FAIL"],
    [CasMessage.TRIM_AIR_OFF]: [MessageLevel.Status, "TRIM AIR OFF"],
    [CasMessage.RAM_AIR_FAIL]: [MessageLevel.Caution, "RAM AIR FAIL"],
    [CasMessage.RAM_AIR_OPEN]: [MessageLevel.Status, "RAM AIR OPEN"],
    [CasMessage.PACK_FLOW_HI]: [MessageLevel.Status, "PACK FLOW HI"],
    [CasMessage.MAN_TEMP_ON]: [MessageLevel.Status, "MAN TEMP ON"],
    [CasMessage.ADS_1_FAIL]: [MessageLevel.Advisory, "ADS 1 FAIL"],
    [CasMessage.ADS_2_FAIL]: [MessageLevel.Advisory, "ADS 2 FAIL"],
    [CasMessage.ADS_3_FAIL]: [MessageLevel.Caution, "ADS 3 FAIL"],
    [CasMessage.ADS_4_FAIL]: [MessageLevel.Advisory, "ADS 4 FAIL"],
    [CasMessage.DUAL_ADS_FAIL]: [MessageLevel.Caution, "DUAL ADS FAIL"],
    [CasMessage.L_PFD_ISI_SAME_ADS]: [MessageLevel.Advisory, "L PFD-ISI SAME ADS"],
    [CasMessage.R_PFD_ISI_SAME_ADS]: [MessageLevel.Advisory, "R PFD-ISI SAME ADS"],
    [CasMessage.ADS_1_PROBE_HEAT_FAIL]: [MessageLevel.Caution, "ADS 1 PROBE HEAT FAIL"],
    [CasMessage.ADS_2_PROBE_HEAT_FAIL]: [MessageLevel.Caution, "ADS 2 PROBE HEAT FAIL"],
    [CasMessage.ADS_3_PROBE_HEAT_FAIL]: [MessageLevel.Caution, "ADS 3 PROBE HEAT FAIL"],
    [CasMessage.ADS_4_PROBE_HEAT_FAIL]: [MessageLevel.Caution, "ADS 4 PROBE HEAT FAIL"],
    [CasMessage.ADS_ISI_PROBE_HEAT]: [MessageLevel.Caution, "ADS ISI PROBE HEAT"],
    [CasMessage.ADS_1_SLIPCOMP_FAIL]: [MessageLevel.Caution, "ADS 1 SLIPCOMP FAIL"],
    [CasMessage.ADS_2_SLIPCOMP_FAIL]: [MessageLevel.Caution, "ADS 2 SLIPCOMP FAIL"],
    [CasMessage.ADS_3_SLIPCOMP_FAIL]: [MessageLevel.Caution, "ADS 3 SLIPCOMP FAIL"],
    [CasMessage.ADS_4_SLIPCOMP_FAIL]: [MessageLevel.Caution, "ADS 4 SLIPCOMP FAIL"],
    [CasMessage.ADS_ISI_SLIPCOMP_FAIL]: [MessageLevel.Caution, "ADS ISI SLIPCOMP FAIL"],
    [CasMessage.ADS_FAULT]: [MessageLevel.Advisory, "ADS FAULT"],
    [CasMessage.ADS_PROBE_HEAT_GND_ON]: [MessageLevel.Status, "ADS PROBE HEAT GND ON"],
    [CasMessage.ADS_1_DEGRADED]: [MessageLevel.Advisory, "ADS 1 DEGRADED"],
    [CasMessage.ADS_2_DEGRADED]: [MessageLevel.Advisory, "ADS 2 DEGRADED"],
    [CasMessage.ADS_3_DEGRADED]: [MessageLevel.Advisory, "ADS 3 DEGRADED"],
    [CasMessage.ADS_4_DEGRADED]: [MessageLevel.Advisory, "ADS 4 DEGRADED"],
    [CasMessage.ADS_MAINT_MODE_ACTIVE]: [MessageLevel.Advisory, "ADS MAINT MODE ACTIVE"],
    [CasMessage.HI_LOAD_MONITOR_FAIL]: [MessageLevel.Advisory, "HI LOAD MONITOR FAIL"],
    [CasMessage.HEALTH_MGMT_FAULT]: [MessageLevel.Advisory, "HEALTH MGMT FAULT"],
    [CasMessage.HI_LOAD_EVENT]: [MessageLevel.Advisory, "HI LOAD EVENT"],
    [CasMessage.APU_OVERSPEED]: [MessageLevel.Warning, "APU OVERSPEED"],
    [CasMessage.APU]: [MessageLevel.Caution, "APU"],
    [CasMessage.APU_BLEED_FAIL]: [MessageLevel.Caution, "APU BLEED FAIL"],
    [CasMessage.APU_DOOR_OPEN]: [MessageLevel.Caution, "APU DOOR OPEN"],
    [CasMessage.APU_OIL_LO_TEMP]: [MessageLevel.Caution, "APU OIL LO TEMP"],
    [CasMessage.APU_IN_START]: [MessageLevel.Status, "APU IN START"],
    [CasMessage.APU_ON]: [MessageLevel.Status, "APU ON"],
    [CasMessage.APU_SHUTDOWN]: [MessageLevel.Advisory, "APU SHUTDOWN"],
    [CasMessage.APU_FAULT]: [MessageLevel.Advisory, "APU FAULT"],
    [CasMessage.APU_OIL_LO_QTY]: [MessageLevel.Advisory, "APU OIL LO QTY"],
    [CasMessage.DISPLAY_REV_MISCONFIG]: [MessageLevel.Status, "DISPLAY REV MISCONFIG"],
    [CasMessage.IPC_1_FAIL]: [MessageLevel.Caution, "IPC 1 FAIL"],
    [CasMessage.IPC_2_FAIL]: [MessageLevel.Caution, "IPC 2 FAIL"],
    [CasMessage.IPC_3_FAIL]: [MessageLevel.Caution, "IPC 3 FAIL"],
    [CasMessage.IPC_4_FAIL]: [MessageLevel.Caution, "IPC 4 FAIL"],
    [CasMessage.RAD_ALT_1_FAIL]: [MessageLevel.Advisory, "RAD ALT 1 FAIL"],
    [CasMessage.RAD_ALT_2_FAIL]: [MessageLevel.Advisory, "RAD ALT 2 FAIL"],
    [CasMessage.RAD_ALT_3_FAIL]: [MessageLevel.Advisory, "RAD ALT 3 FAIL"],
    [CasMessage.RAD_ALT_FAIL]: [MessageLevel.Caution, "RAD ALT FAIL"],
    [CasMessage.AUTO_FLIGHT_FAULT]: [MessageLevel.Advisory, "AUTO FLIGHT FAULT"],
    [CasMessage.AT_RETARD_INHIBIT]: [MessageLevel.Caution, "AT RETARD INHIBIT"],
    [CasMessage.FD_MODE_CHANGE]: [MessageLevel.Caution, "FD MODE CHANGE"],
    [CasMessage.CONFIG_AP]: [MessageLevel.Warning, "CONFIG AP"],
    [CasMessage.EMER_DESCENT_WARN]: [MessageLevel.Warning, "EMERGENCY DESCENT"],
    [CasMessage.EMER_DESCENT_CAUT]: [MessageLevel.Caution, "EMERGENCY DESCENT"],
    [CasMessage.CONFIG_AT]: [MessageLevel.Warning, "CONFIG AT"],
    [CasMessage.CONFIG_THRUST_LEVER]: [MessageLevel.Warning, "CONFIG THRUST LEVER"],
    [CasMessage.L_ENG_AT_OFF]: [MessageLevel.Advisory, "L ENG A/T OFF"],
    [CasMessage.R_ENG_AT_OFF]: [MessageLevel.Advisory, "R ENG A/T OFF"],
    [CasMessage.FMS_OEI_PERF_ACTIVE]: [MessageLevel.Caution, "FMS OEI PERF ACTIVE"],
    [CasMessage.APPR1_NOT_AVAIL]: [MessageLevel.Advisory, "APPR1 NOT AVAIL"],
    [CasMessage.APPR2_NOT_AVAIL]: [MessageLevel.Advisory, "APPR2 NOT AVAIL"],
    [CasMessage.LAND2_NOT_AVAIL]: [MessageLevel.Advisory, "LAND2 NOT AVAIL"],
    [CasMessage.LAND3_NOT_AVAIL]: [MessageLevel.Advisory, "LAND3 NOT AVAIL"],
    [CasMessage.WXR_ON]: [MessageLevel.Caution, "WXR ON"],
    [CasMessage.L_R_RADIO_TUNING_FAIL]: [MessageLevel.Caution, "L-R RADIO TUNING FAIL"],
    [CasMessage.L_CTP_TUNING_FAIL]: [MessageLevel.Caution, "L CTP TUNING FAIL"],
    [CasMessage.R_CTP_TUNING_FAIL]: [MessageLevel.Caution, "R CTP TUNING FAIL"],
    [CasMessage.AURAL_FAIL]: [MessageLevel.Caution, "AURAL WARN FAIL"],
    [CasMessage.AURAL_WARN_INHIB]: [MessageLevel.Status, "AURAL WARN INHIB"],
    [CasMessage.AUDIO_PNL_1_FAIL]: [MessageLevel.Advisory, "AUDIO PNL 1 FAIL"],
    [CasMessage.AUDIO_PNL_2_FAIL]: [MessageLevel.Advisory, "AUDIO PNL 2 FAIL"],
    [CasMessage.SELCAL]: [MessageLevel.Advisory, "SELCAL"],
    [CasMessage.VHF_COM_121_5_ENABLE]: [MessageLevel.Status, "VHF COM 121.5 ENABLE"],
    [CasMessage.DATALINK_FAIL]: [MessageLevel.Advisory, "DATALINK FAIL"],
    [CasMessage.DATALINK_STATUS]: [MessageLevel.Advisory, "DATALINK STATUS"],
    [CasMessage.SATCOM_FAIL]: [MessageLevel.Advisory, "SATCOM FAIL"],
    [CasMessage.SATCOM_NO_SIGNAL]: [MessageLevel.Advisory, "SATCOM NO SIGNAL"],
    [CasMessage.SATCOM_DATA_FAIL]: [MessageLevel.Advisory, "SATCOM DATA FAIL"],
    [CasMessage.SATCOM_VOICE_FAIL]: [MessageLevel.Advisory, "SATCOM VOICE FAIL"],
    [CasMessage.SAT_VOICE_NO_SIGNAL]: [MessageLevel.Advisory, "SAT VOICE NO SIGNAL"],
    [CasMessage.VHF3_IN_VOICE]: [MessageLevel.Status, "VHF3 IN VOICE"],
    [CasMessage.DSPL_TUNE_INHIB]: [MessageLevel.Status, "DSPL TUNE INHIB"],
    [CasMessage.CURSOR_INHIB]: [MessageLevel.Status, "CURSOR INHIB"],
    [CasMessage.CTP_OVERRIDE]: [MessageLevel.Status, "CTP OVERRIDE"],
    [CasMessage.EFIS_COMPARATOR_FAIL]: [MessageLevel.Caution, "EFIS COMPARATOR FAIL"],
    [CasMessage.EFIS_MISCOMPARE]: [MessageLevel.Caution, "EFIS MISCOMPARE"],
    [CasMessage.ENG_DSPL_MISCOMPARE]: [MessageLevel.Caution, "ENG DSPL MISCOMPARE"],
    [CasMessage.HUD_FAIL]: [MessageLevel.Advisory, "HUD FAIL"],
    [CasMessage.L_HUD_FAIL]: [MessageLevel.Advisory, "L HUD FAIL"],
    [CasMessage.R_HUD_FAIL]: [MessageLevel.Advisory, "R HUD FAIL"],
    [CasMessage.LVTO_NOT_AVAIL]: [MessageLevel.Advisory, "LVTO NOT AVAIL"],
    [CasMessage.L_LVTO_NOT_AVAIL]: [MessageLevel.Advisory, "L LVTO NOT AVAIL"],
    [CasMessage.R_LVTO_NOT_AVAIL]: [MessageLevel.Advisory, "R LVTO NOT AVAIL"],
    [CasMessage.CAS_MISCOMPARE]: [MessageLevel.Advisory, "CAS MISCOMPARE"],
    [CasMessage.DMC_1A_FAIL]: [MessageLevel.Advisory, "DMC 1A FAIL"],
    [CasMessage.DMC_1B_FAIL]: [MessageLevel.Advisory, "DMC 1B FAIL"],
    [CasMessage.DMC_2A_FAIL]: [MessageLevel.Advisory, "DMC 2A FAIL"],
    [CasMessage.DMC_2B_FAIL]: [MessageLevel.Advisory, "DMC 2B FAIL"],
    [CasMessage.AT_FAIL]: [MessageLevel.Advisory, "AT FAIL"],
    [CasMessage.FD_FAIL]: [MessageLevel.Caution, "FD FAIL"],
    [CasMessage.DMC_1_FAIL]: [MessageLevel.Caution, "DMC 1 FAIL"],
    [CasMessage.DMC_2_FAIL]: [MessageLevel.Caution, "DMC 2 FAIL"],
    [CasMessage.TCAS_FAIL]: [MessageLevel.Caution, "TCAS FAIL"],
    [CasMessage.TCAS_OFF]: [MessageLevel.Caution, "TCAS OFF"],
    [CasMessage.TAWS_FAIL]: [MessageLevel.Caution, "TAWS FAIL"],
    [CasMessage.GROUND_PROX_FAIL]: [MessageLevel.Advisory, "TAWS GPWS FAIL"],
    [CasMessage.WINDSHEAR_FAIL]: [MessageLevel.Advisory, "TAWS WINDSHEAR FAIL"],
    [CasMessage.TAWS_MAP_FAIL]: [MessageLevel.Advisory, "TAWS MAP FAIL"],
    [CasMessage.TAWS_TERRAIN_FAIL]: [MessageLevel.Advisory, "TAWS TERR FAIL"],
    [CasMessage.TAWS_GS_CNCL]: [MessageLevel.Status, "TAWS GS CNCL"],
    [CasMessage.TAWS_FLAP_INHIB]: [MessageLevel.Status, "TAWS FLAP INHIB"],
    [CasMessage.TAWS_TERR_INHIB]: [MessageLevel.Status, "TAWS TERR INHIB"],
    [CasMessage.TAWS_GEAR_INHIB]: [MessageLevel.Status, "TAWS GEAR INHIB"],
    [CasMessage.WXR_FAIL]: [MessageLevel.Advisory, "WXR FAIL"],
    [CasMessage.WXR_CTRL_FAULT]: [MessageLevel.Advisory, "WXR CTRL FAULT"],
    [CasMessage.WXR_FAULT]: [MessageLevel.Advisory, "WXR FAULT"],
    [CasMessage.WXR_TURB_FAULT]: [MessageLevel.Advisory, "WXR TURB FAULT"],
    [CasMessage.WXR_AUTO_FAULT]: [MessageLevel.Advisory, "WXR AUTO FAULT"],
    [CasMessage.WXR_PWS_FAIL]: [MessageLevel.Advisory, "WXR PWS FAIL"],
    [CasMessage.XPDR_1_FAIL]: [MessageLevel.Caution, "XPDR 1 FAIL"],
    [CasMessage.XPDR_2_FAIL]: [MessageLevel.Caution, "XPDR 2 FAIL"],
    [CasMessage.ADSB_OUT_FAIL]: [MessageLevel.Caution, "ADS-B OUT FAIL"],
    [CasMessage.ADSB_1_OUT_FAIL]: [MessageLevel.Caution, "ADS-B 1 OUT FAIL"],
    [CasMessage.ADSB_2_OUT_FAIL]: [MessageLevel.Caution, "ADS-B 2 OUT FAIL"],
    [CasMessage.SMS_RUNWAY_INHIB]: [MessageLevel.Status, "SMS RUNWAY INHIB"],
    [CasMessage.SMS_RUNWAY_N_A]: [MessageLevel.Advisory, "SMS RUNWAY N/A"],
    [CasMessage.SMS_FAIL]: [MessageLevel.Advisory, "SMS FAIL"],
    [CasMessage.FMS_1_FAIL]: [MessageLevel.Caution, "FMS 1 FAIL"],
    [CasMessage.FMS_2_FAIL]: [MessageLevel.Caution, "FMS 2 FAIL"],
    [CasMessage.FMS_FUEL]: [MessageLevel.Caution, "FMS FUEL"],
    [CasMessage.APPROACH_NOT_AVAIL]: [MessageLevel.Caution, "APPROACH NOT AVAIL"],
    [CasMessage.FMS_POSITION]: [MessageLevel.Caution, "FMS POSITION"],
    [CasMessage.LPV_NOT_AVAIL]: [MessageLevel.Caution, "LPV NOT AVAIL"],
    [CasMessage.UNABLE_RNP]: [MessageLevel.Caution, "UNABLE RNP"],
    [CasMessage.GNSS_NOT_AVAILABLE]: [MessageLevel.Caution, "GNSS NOT AVAIL"],
    [CasMessage.FMS_PERF_DEP_VSPEEDS]: [MessageLevel.Caution, "FMS PERF DEP VSPEEDS"],
    [CasMessage.FMS_PERF_DEP_CONFIG]: [MessageLevel.Caution, "FMS PERF DEP CONFIG"],
    [CasMessage.AC_MAINTENANCE_SW]: [MessageLevel.Status, "A/C MAINTENANCE SW"],
    [CasMessage.AVIONIC_FAULT]: [MessageLevel.Advisory, "AVIONIC FAULT"],
    [CasMessage.AVIONIC_FAN_FAULT]: [MessageLevel.Advisory, "AVIONIC FAN FAULT"],
    [CasMessage.L_BLEED_LEAK]: [MessageLevel.Caution, "L BLEED LEAK"],
    [CasMessage.R_BLEED_LEAK]: [MessageLevel.Caution, "R BLEED LEAK"],
    [CasMessage.WING_A_ICE_LEAK]: [MessageLevel.Caution, "WING A/ICE LEAK"],
    [CasMessage.APU_BLEED_LEAK]: [MessageLevel.Caution, "APU BLEED LEAK"],
    [CasMessage.L_PACK_LEAK]: [MessageLevel.Caution, "L PACK LEAK"],
    [CasMessage.R_PACK_LEAK]: [MessageLevel.Caution, "R PACK LEAK"],
    [CasMessage.TRIM_AIR_LEAK]: [MessageLevel.Caution, "TRIM AIR LEAK"],
    [CasMessage.LEAK_DET_FAIL]: [MessageLevel.Caution, "LEAK DET FAIL"],
    [CasMessage.L_BLEED_FAIL]: [MessageLevel.Caution, "L BLEED FAIL"],
    [CasMessage.R_BLEED_FAIL]: [MessageLevel.Caution, "R BLEED FAIL"],
    [CasMessage.L_BLEED_OVHT]: [MessageLevel.Caution, "L BLEED OVHT"],
    [CasMessage.R_BLEED_OVHT]: [MessageLevel.Caution, "R BLEED OVHT"],
    [CasMessage.L_BLEED_OFF]: [MessageLevel.Status, "L BLEED OFF"],
    [CasMessage.R_BLEED_OFF]: [MessageLevel.Status, "R BLEED OFF"],
    [CasMessage.ENG_BLEED_MISCONFIG]: [MessageLevel.Caution, "ENG BLEED MISCONFIG"],
    [CasMessage.XBLEED_FAIL]: [MessageLevel.Caution, "XBLEED FAIL"],
    [CasMessage.XBLEED_MAN_CLSD]: [MessageLevel.Status, "XBLEED MAN CLSD"],
    [CasMessage.XBLEED_MAN_OPEN]: [MessageLevel.Status, "XBLEED MAN OPEN"],
    [CasMessage.APU_BLEED_OFF]: [MessageLevel.Status, "APU BLEED OFF"],
    [CasMessage.CONFIG_BRAKE]: [MessageLevel.Warning, "CONFIG BRAKE"],
    [CasMessage.BRAKE_OVHT]: [MessageLevel.Warning, "BRAKE OVHT"],
    [CasMessage.BRAKE_ON]: [MessageLevel.Caution, "BRAKE ON"],
    [CasMessage.NORM_BRAKE_FAIL]: [MessageLevel.Caution, "NORM BRAKE FAIL"],
    [CasMessage.ALTN_BRAKE_FAIL]: [MessageLevel.Advisory, "ALTN BRAKE FAIL"],
    [CasMessage.BRAKE_FAIL]: [MessageLevel.Caution, "BRAKE FAIL"],
    [CasMessage.PARK_BRAKE_FAIL]: [MessageLevel.Caution, "PARK BRAKE FAIL"],
    [CasMessage.PLT_BRAKE_PEDAL_FAIL]: [MessageLevel.Caution, "PLT BRAKE PEDAL FAIL"],
    [CasMessage.CPLT_BRAKE_PEDAL_FAIL]: [MessageLevel.Caution, "CPLT BRAKE PEDAL FAIL"],
    [CasMessage.L_BRAKE_FAIL]: [MessageLevel.Caution, "L BRAKE FAIL"],
    [CasMessage.R_BRAKE_FAIL]: [MessageLevel.Caution, "R BRAKE FAIL"],
    [CasMessage.AUTOBRAKE_FAIL]: [MessageLevel.Caution, "AUTOBRAKE FAIL"],
    [CasMessage.BRAKE_TEMP]: [MessageLevel.Advisory, "BRAKE TEMP"],
    [CasMessage.L_BRAKE_DEGRADED]: [MessageLevel.Advisory, "L BRAKE DEGRADED"],
    [CasMessage.R_BRAKE_DEGRADED]: [MessageLevel.Advisory, "R BRAKE DEGRADED"],
    [CasMessage.BRAKE_FAULT]: [MessageLevel.Advisory, "BRAKE FAULT"],
    [CasMessage.PARK_BRAKE_ON]: [MessageLevel.Status, "PARK BRAKE ON"],
    [CasMessage.ALTN_BRAKE_ON]: [MessageLevel.Status, "ALTN BRAKE ON"],
    [CasMessage.AUTOBRAKE_RTO]: [MessageLevel.Status, "AUTOBRAKE RTO"],
    [CasMessage.AUTOBRAKE_HI]: [MessageLevel.Status, "AUTOBRAKE HI"],
    [CasMessage.AUTOBRAKE_MED]: [MessageLevel.Status, "AUTOBRAKE MED"],
    [CasMessage.AUTOBRAKE_LO]: [MessageLevel.Status, "AUTOBRAKE LO"],
    [CasMessage.CARGO_DOOR]: [MessageLevel.Caution, "CARGO DOOR"],
    [CasMessage.CABIN_COM_FAULT]: [MessageLevel.Advisory, "CABIN COM FAULT"],
    [CasMessage.SEAT_BELTS]: [MessageLevel.Status, "SEAT BELTS"],
    [CasMessage.NO_PED]: [MessageLevel.Status, "NO PED"],
    [CasMessage.CABIN_DIFF_PRESS]: [MessageLevel.Warning, "CABIN DIFF PRESS"],
    [CasMessage.CABIN_ALT_WARN]: [MessageLevel.Warning, "CABIN ALT"],
    [CasMessage.CABIN_ALT_CAUT]: [MessageLevel.Caution, "CABIN ALT"],
    [CasMessage.AUTO_PRESS_FAIL]: [MessageLevel.Caution, "AUTO PRESS FAIL"],
    [CasMessage.EMER_DEPRESS_ON]: [MessageLevel.Caution, "EMER DEPRESS ON"],
    [CasMessage.DITCHING_ON]: [MessageLevel.Status, "DITCHING ON"],
    [CasMessage.DITCHING_MISCONFIG]: [MessageLevel.Caution, "DITCHING MISCONFIG"],
    [CasMessage.CABIN_PRESS_MAN]: [MessageLevel.Status, "CABIN PRESS MAN"],
    [CasMessage.CABIN_ALT_LEVEL_HI]: [MessageLevel.Advisory, "CABIN ALT LEVEL HI"],
    [CasMessage.LDG_ELEV_MISCONFIG]: [MessageLevel.Caution, "LDG ELEV MISCONFIG"],
    [CasMessage.CVR_FAIL]: [MessageLevel.Advisory, "CVR FAIL"],
    [CasMessage.FDR_FAIL]: [MessageLevel.Advisory, "FDR FAIL"],
    [CasMessage.PILOT_EVENT]: [MessageLevel.Status, "PILOT EVENT"],
    [CasMessage.FDR_ACCEL_FAIL]: [MessageLevel.Advisory, "FDR ACCEL FAIL"],
    [CasMessage.RECIRC_AIR_FAIL]: [MessageLevel.Caution, "RECIRC AIR FAIL"],
    [CasMessage.RECIRC_AIR_OFF]: [MessageLevel.Status, "RECIRC AIR OFF"],
    [CasMessage.FWD_CARGO_HEAT_FAIL]: [MessageLevel.Caution, "FWD CARGO HEAT FAIL"],
    [CasMessage.FWD_CARGO_LO_TEMP]: [MessageLevel.Caution, "FWD CARGO LO TEMP"],
    [CasMessage.FWD_CARGO_AIR_OFF]: [MessageLevel.Status, "FWD CARGO AIR OFF"],
    [CasMessage.AFT_CARGO_AIR_OFF]: [MessageLevel.Status, "AFT CARGO AIR OFF"],
    [CasMessage.EMER_PWR_ONLY]: [MessageLevel.Warning, "EMER PWR ONLY"],
    [CasMessage.BATT_EMER_PWR_ON]: [MessageLevel.Advisory, "BATT EMER PWR ON"],
    [CasMessage.BATT_1_OVERTEMP]: [MessageLevel.Caution, "BATT 1 OVERTEMP"],
    [CasMessage.BATT_2_OVERTEMP]: [MessageLevel.Caution, "BATT 2 OVERTEMP"],
    [CasMessage.APU_GEN_FAIL]: [MessageLevel.Caution, "APU GEN FAIL"],
    [CasMessage.BATT_DISCHARGING]: [MessageLevel.Caution, "BATT DISCHARGING"],
    [CasMessage.BATT_1_FAIL]: [MessageLevel.Caution, "BATT 1 FAIL"],
    [CasMessage.BATT_2_FAIL]: [MessageLevel.Caution, "BATT 2 FAIL"],
    [CasMessage.L_GEN_FAIL]: [MessageLevel.Caution, "L GEN FAIL"],
    [CasMessage.L_GEN_OIL]: [MessageLevel.Caution, "L GEN OIL"],
    [CasMessage.R_GEN_FAIL]: [MessageLevel.Caution, "R GEN FAIL"],
    [CasMessage.R_GEN_OIL]: [MessageLevel.Caution, "R GEN OIL"],
    [CasMessage.AC_BUS_1]: [MessageLevel.Caution, "AC BUS 1"],
    [CasMessage.AC_BUS_2]: [MessageLevel.Caution, "AC BUS 2"],
    [CasMessage.AC_ESS_BUS]: [MessageLevel.Caution, "AC ESS BUS"],
    [CasMessage.DC_BUS_1]: [MessageLevel.Caution, "DC BUS 1"],
    [CasMessage.DC_BUS_2]: [MessageLevel.Caution, "DC BUS 2"],
    [CasMessage.DC_ESS_BUS_1]: [MessageLevel.Caution, "DC ESS BUS 1"],
    [CasMessage.DC_ESS_BUS_2]: [MessageLevel.Caution, "DC ESS BUS 2"],
    [CasMessage.DC_ESS_BUS_3]: [MessageLevel.Caution, "DC ESS BUS 3"],
    [CasMessage.DC_EMER_BUS]: [MessageLevel.Caution, "DC EMER BUS"],
    [CasMessage.RAT_GEN_FAIL]: [MessageLevel.Caution, "RAT GEN FAIL"],
    [CasMessage.TRU_FAULT]: [MessageLevel.Advisory, "TRU FAULT"],
    [CasMessage.CB_TRIP]: [MessageLevel.Advisory, "CB TRIP"],
    [CasMessage.ELECTRICAL_FAULT]: [MessageLevel.Advisory, "ELECTRICAL FAULT"],
    [CasMessage.LOAD_SHED]: [MessageLevel.Advisory, "LOAD SHED"],
    [CasMessage.BATT_CHARGER_FAULT]: [MessageLevel.Advisory, "BATT CHARGER FAULT"],
    [CasMessage.RAT_DPLY_ADV]: [MessageLevel.Advisory, "RAT DPLY"],
    [CasMessage.RAT_GEN_ON]: [MessageLevel.Advisory, "RAT GEN ON"],
    [CasMessage.EXT_PWR_AVAIL]: [MessageLevel.Advisory, "EXT PWR AVAIL"],
    [CasMessage.EXT_PWR_IN_USE]: [MessageLevel.Status, "EXT PWR IN USE"],
    [CasMessage.ELEC_BUS_ISOL_MAIN]: [MessageLevel.Status, "ELEC BUS ISOL MAIN"],
    [CasMessage.ELEC_BUS_ISOL_ESS]: [MessageLevel.Status, "ELEC BUS ISOL ESS"],
    [CasMessage.CABIN_PWR_OFF]: [MessageLevel.Status, "CABIN PWR OFF"],
    [CasMessage.L_GEN_OFF]: [MessageLevel.Status, "L GEN OFF"],
    [CasMessage.L_GEN_DISC]: [MessageLevel.Status, "L GEN DISC"],
    [CasMessage.R_GEN_OFF]: [MessageLevel.Status, "R GEN OFF"],
    [CasMessage.R_GEN_DISC]: [MessageLevel.Status, "R GEN DISC"],
    [CasMessage.APU_GEN_OFF]: [MessageLevel.Status, "APU GEN OFF"],
    [CasMessage.BATT_PWR_CONFIG]: [MessageLevel.Status, "BATT PWR CONFIG"],
    [CasMessage.BATT_1_OFF]: [MessageLevel.Status, "BATT 1 OFF"],
    [CasMessage.BATT_2_OFF]: [MessageLevel.Status, "BATT 2 OFF"],
    [CasMessage.ELT_ON]: [MessageLevel.Caution, "ELT ON"],
    [CasMessage.ELT_DT_ON]: [MessageLevel.Caution, "ELT ON (distress tracking)"],
    [CasMessage.ELT_DT_FAIL]: [MessageLevel.Advisory, "ELT FAIL"],
    [CasMessage.ELT_DT_FAULT]: [MessageLevel.Advisory, "ELT FAULT"],
    [CasMessage.EQUIP_BAY_DOOR]: [MessageLevel.Caution, "EQUIP BAY DOOR"],
    [CasMessage.L_ENG_SHUTDOWN]: [MessageLevel.Status, "L ENG SHUTDOWN"],
    [CasMessage.R_ENG_SHUTDOWN]: [MessageLevel.Status, "R ENG SHUTDOWN"],
    [CasMessage.L_ENG_FAIL]: [MessageLevel.Caution, "L ENG FAIL"],
    [CasMessage.R_ENG_FAIL]: [MessageLevel.Caution, "R ENG FAIL"],
    [CasMessage.DUAL_ENG_FAIL]: [MessageLevel.Warning, "DUAL ENG FAIL"],
    [CasMessage.L_ENG_EXCEEDANCE]: [MessageLevel.Caution, "L ENG EXCEEDANCE"],
    [CasMessage.R_ENG_EXCEEDANCE]: [MessageLevel.Caution, "R ENG EXCEEDANCE"],
    [CasMessage.L_THROTTLE_FAIL]: [MessageLevel.Caution, "L THROTTLE FAIL"],
    [CasMessage.R_THROTTLE_FAIL]: [MessageLevel.Caution, "R THROTTLE FAIL"],
    [CasMessage.ENG_SETTING_MISMATCH]: [MessageLevel.Caution, "ENG SETTING MISMATCH"],
    [CasMessage.L_ENGINE_FAULT]: [MessageLevel.Advisory, "L ENGINE FAULT"],
    [CasMessage.R_ENGINE_FAULT]: [MessageLevel.Advisory, "R ENGINE FAULT"],
    [CasMessage.ENG_VIBRATION]: [MessageLevel.Caution, "ENG VIBRATION"],
    [CasMessage.L_ENG_START_ABORT]: [MessageLevel.Caution, "L ENG START ABORT"],
    [CasMessage.R_ENG_START_ABORT]: [MessageLevel.Caution, "R ENG START ABORT"],
    [CasMessage.L_ENG_STARTER_FAIL_ON]: [MessageLevel.Caution, "L ENG STARTER FAIL ON"],
    [CasMessage.R_ENG_STARTER_FAIL_ON]: [MessageLevel.Caution, "R ENG STARTER FAIL ON"],
    [CasMessage.ENG_CONT_IGNITION_ON]: [MessageLevel.Status, "ENG CONT IGNITION ON"],
    [CasMessage.L_REVERSER_FAIL]: [MessageLevel.Caution, "L REVERSER FAIL"],
    [CasMessage.R_REVERSER_FAIL]: [MessageLevel.Caution, "R REVERSER FAIL"],
    [CasMessage.L_REVERSER_UNLOCK]: [MessageLevel.Caution, "L REVERSER UNLOCK"],
    [CasMessage.R_REVERSER_UNLOCK]: [MessageLevel.Caution, "R REVERSER UNLOCK"],
    [CasMessage.L_REVERSER_INHIBIT]: [MessageLevel.Status, "L REVERSER INHIBIT"],
    [CasMessage.R_REVERSER_INHIBIT]: [MessageLevel.Status, "R REVERSER INHIBIT"],
    [CasMessage.THROTTLE_IN_REVERSE]: [MessageLevel.Caution, "THROTTLE IN REVERSE"],
    [CasMessage.L_COWL_A_ICE_FAIL]: [MessageLevel.Caution, "L COWL A/ICE FAIL"],
    [CasMessage.R_COWL_A_ICE_FAIL]: [MessageLevel.Caution, "R COWL A/ICE FAIL"],
    [CasMessage.L_COWL_A_ICE_ON]: [MessageLevel.Status, "L COWL A/ICE ON"],
    [CasMessage.R_COWL_A_ICE_ON]: [MessageLevel.Status, "R COWL A/ICE ON"],
    [CasMessage.L_R_COWL_A_ICE_ON]: [MessageLevel.Status, "L-R COWL A/ICE ON"],
    [CasMessage.COWL_A_ICE_ON]: [MessageLevel.Caution, "COWL A/ICE ON"],
    [CasMessage.L_COWL_A_ICE_FAIL_ON]: [MessageLevel.Caution, "L COWL A/ICE FAIL ON"],
    [CasMessage.R_COWL_A_ICE_FAIL_ON]: [MessageLevel.Caution, "R COWL A/ICE FAIL ON"],
    [CasMessage.L_COWL_A_ICE_OFF]: [MessageLevel.Status, "L COWL A/ICE OFF"],
    [CasMessage.R_COWL_A_ICE_OFF]: [MessageLevel.Status, "R COWL A/ICE OFF"],
    [CasMessage.L_R_COWL_A_ICE_OFF]: [MessageLevel.Status, "L-R COWL A/ICE OFF"],
    [CasMessage.L_ENG_OIL_PRESS]: [MessageLevel.Warning, "L ENG OIL PRESS"],
    [CasMessage.R_ENG_OIL_PRESS]: [MessageLevel.Warning, "R ENG OIL PRESS"],
    [CasMessage.L_ENG_OIL_LO_QTY]: [MessageLevel.Advisory, "L ENG OIL LO QTY"],
    [CasMessage.R_ENG_OIL_LO_QTY]: [MessageLevel.Advisory, "R ENG OIL LO QTY"],
    [CasMessage.APR_DISARMED]: [MessageLevel.Status, "APR DISARM"],
    [CasMessage.L_ENG_OPER_DEGRADED]: [MessageLevel.Caution, "L ENG OPER DEGRADED"],
    [CasMessage.R_ENG_OPER_DEGRADED]: [MessageLevel.Caution, "R ENG OPER DEGRADED"],
    [CasMessage.ENG_OIL_LO_TEMP]: [MessageLevel.Caution, "ENG OIL LO TEMP"],
    [CasMessage.L_ENG_FUEL_FILTER]: [MessageLevel.Advisory, "L ENG FUEL FILTER"],
    [CasMessage.R_ENG_FUEL_FILTER]: [MessageLevel.Advisory, "R ENG FUEL FILTER"],
    [CasMessage.L_R_ENG_FUEL_FILTER]: [MessageLevel.Caution, "L-R ENG FUEL FILTER"],
    [CasMessage.L_ENG_OIL_FILTER]: [MessageLevel.Caution, "L ENG OIL FILTER"],
    [CasMessage.R_ENG_OIL_FILTER]: [MessageLevel.Caution, "R ENG OIL FILTER"],
    [CasMessage.L_ENG_NACELLE_OVHT]: [MessageLevel.Caution, "L ENG NACELLE OVHT"],
    [CasMessage.R_ENG_NACELLE_OVHT]: [MessageLevel.Caution, "R ENG NACELLE OVHT"],
    [CasMessage.L_ENG_PCE_DOOR_OPEN]: [MessageLevel.Advisory, "L ENG PCE DOOR OPEN"],
    [CasMessage.R_ENG_PCE_DOOR_OPEN]: [MessageLevel.Advisory, "R ENG PCE DOOR OPEN"],
    [CasMessage.L_FUEL_FLOW_DEGRADED]: [MessageLevel.Advisory, "L FUEL FLOW DEGRADED"],
    [CasMessage.R_FUEL_FLOW_DEGRADED]: [MessageLevel.Advisory, "R FUEL FLOW DEGRADED"],
    [CasMessage.L_ENG_STARTER_OVHT]: [MessageLevel.Advisory, "L ENG STARTER OVHT"],
    [CasMessage.R_ENG_STARTER_OVHT]: [MessageLevel.Advisory, "R ENG STARTER OVHT"],
    [CasMessage.ENG_START_DELAY]: [MessageLevel.Advisory, "ENG START DELAY"],
    [CasMessage.CKPT_DOOR_LOCK_FAIL]: [MessageLevel.Caution, "CKPT DOOR LOCK FAIL"],
    [CasMessage.CKPT_DOOR_OPEN]: [MessageLevel.Advisory, "CKPT DOOR OPEN"],
    [CasMessage.CKPT_DOOR_LOCK_OFF]: [MessageLevel.Status, "CKPT DOOR LOCK OFF"],
    [CasMessage.CKPT_DOOR_EMER_ACCESS]: [MessageLevel.Warning, "CKPT DOOR EMER ACCESS"],
    [CasMessage.FUEL_INERTING_FAULT]: [MessageLevel.Advisory, "FUEL INERTING FAULT"],
    [CasMessage.L_FUEL_LO_QTY]: [MessageLevel.Caution, "L FUEL LO QTY"],
    [CasMessage.R_FUEL_LO_QTY]: [MessageLevel.Caution, "R FUEL LO QTY"],
    [CasMessage.FUEL_TANK_LO_TEMP]: [MessageLevel.Caution, "FUEL TANK LO TEMP"],
    [CasMessage.FUEL_TANK_HI_TEMP]: [MessageLevel.Caution, "FUEL TANK HI TEMP"],
    [CasMessage.FUEL_IMBALANCE]: [MessageLevel.Caution, "FUEL IMBALANCE"],
    [CasMessage.L_ENG_FUEL_SOV_FAIL]: [MessageLevel.Caution, "L ENG FUEL SOV FAIL"],
    [CasMessage.R_ENG_FUEL_SOV_FAIL]: [MessageLevel.Caution, "R ENG FUEL SOV FAIL"],
    [CasMessage.APU_FUEL_SOV_FAIL]: [MessageLevel.Caution, "APU FUEL SOV FAIL"],
    [CasMessage.L_ENG_FUEL_LO_PRESS]: [MessageLevel.Caution, "L ENG FUEL LO PRESS"],
    [CasMessage.R_ENG_FUEL_LO_PRESS]: [MessageLevel.Caution, "R ENG FUEL LO PRESS"],
    [CasMessage.FUEL_CTR_XFR_FAIL]: [MessageLevel.Caution, "FUEL CTR XFR FAIL"],
    [CasMessage.FUEL_MAN_XFR_FAIL]: [MessageLevel.Caution, "FUEL MAN XFR FAIL"],
    [CasMessage.FUEL_COLLECTOR_LO_LVL]: [MessageLevel.Caution, "FUEL COLLECTOR LO LVL"],
    [CasMessage.FUEL_LEAK_SUSPECT]: [MessageLevel.Caution, "FUEL LEAK SUSPECT"],
    [CasMessage.FUEL_MAN_XFR_COMPLETE]: [MessageLevel.Advisory, "FUEL MAN XFR COMPLETE"],
    [CasMessage.FUEL_GRAV_XFR_FAIL]: [MessageLevel.Advisory, "FUEL GRAV XFR FAIL"],
    [CasMessage.FUEL_CTR_XFR_FAULT]: [MessageLevel.Advisory, "FUEL CTR XFR FAULT"],
    [CasMessage.L_BOOST_PUMP_FAIL]: [MessageLevel.Advisory, "L BOOST PUMP FAIL"],
    [CasMessage.R_BOOST_PUMP_FAIL]: [MessageLevel.Advisory, "R BOOST PUMP FAIL"],
    [CasMessage.L_FUEL_EJECTOR_FAIL]: [MessageLevel.Advisory, "L FUEL EJECTOR FAIL"],
    [CasMessage.R_FUEL_EJECTOR_FAIL]: [MessageLevel.Advisory, "R FUEL EJECTOR FAIL"],
    [CasMessage.FUEL_COMPUTER_FAIL]: [MessageLevel.Advisory, "FUEL COMPUTER FAIL"],
    [CasMessage.FUEL_FAULT]: [MessageLevel.Advisory, "FUEL FAULT"],
    [CasMessage.L_ENG_FUEL_SOV_CLSD]: [MessageLevel.Advisory, "L ENG FUEL SOV CLSD"],
    [CasMessage.R_ENG_FUEL_SOV_CLSD]: [MessageLevel.Advisory, "R ENG FUEL SOV CLSD"],
    [CasMessage.APU_FUEL_SOV_CLSD]: [MessageLevel.Advisory, "APU FUEL SOV CLSD"],
    [CasMessage.L_BOOST_PUMP_ON]: [MessageLevel.Status, "L BOOST PUMP ON"],
    [CasMessage.R_BOOST_PUMP_ON]: [MessageLevel.Status, "R BOOST PUMP ON"],
    [CasMessage.L_BOOST_PUMP_OFF]: [MessageLevel.Status, "L BOOST PUMP OFF"],
    [CasMessage.R_BOOST_PUMP_OFF]: [MessageLevel.Status, "R BOOST PUMP OFF"],
    [CasMessage.FUEL_MAN_XFR_TO_L]: [MessageLevel.Status, "FUEL MAN XFR TO L"],
    [CasMessage.FUEL_MAN_XFR_TO_R]: [MessageLevel.Status, "FUEL MAN XFR TO R"],
    [CasMessage.FUEL_MAN_XFR_TO_CTR]: [MessageLevel.Status, "FUEL MAN XFR TO CTR"],
    [CasMessage.FUEL_GRAV_XFR_ON]: [MessageLevel.Status, "FUEL GRAV XFR ON"],
    [CasMessage.FUEL_XFR_CTR_READY]: [MessageLevel.Status, "FUEL XFR CTR READY"],
    [CasMessage.FUEL_ACT_XFR_FAIL]: [MessageLevel.Caution, "FUEL ACT XFR FAIL"],
    [CasMessage.FUEL_ACT_XFR_DEGRADED]: [MessageLevel.Caution, "FUEL ACT XFR DEGRADED"],
    [CasMessage.FUEL_ACT_ISOLATED]: [MessageLevel.Caution, "FUEL ACT ISOLATED"],
    [CasMessage.FUEL_ACT_SOV_OPEN]: [MessageLevel.Status, "FUEL ACT SOV OPEN"],
    [CasMessage.FUEL_ACT_SOV_CLOSED]: [MessageLevel.Status, "FUEL ACT SOV CLOSED"],
    [CasMessage.FUEL_ACT_XFR_OFF]: [MessageLevel.Status, "FUEL ACT XFR OFF"],
    [CasMessage.FUEL_ACT_XFR_BACKUP]: [MessageLevel.Status, "FUEL ACT XFR BACKUP"],
    [CasMessage.FUEL_ACT_FAULT]: [MessageLevel.Advisory, "FUEL ACT FAULT"],
    [CasMessage.FUEL_QUANTITY_FAULT]: [MessageLevel.Advisory, "FUEL QUANTITY FAULT"],
    [CasMessage.CONFIG_FLAP]: [MessageLevel.Warning, "CONFIG FLAP"],
    [CasMessage.SLAT_SKEW]: [MessageLevel.Caution, "SLAT SKEW"],
    [CasMessage.SLAT_FLAP_LEVER_FAIL]: [MessageLevel.Caution, "SLAT FLAP LEVER FAIL"],
    [CasMessage.FLAP_FAIL]: [MessageLevel.Caution, "FLAP FAIL"],
    [CasMessage.SLAT_FAIL]: [MessageLevel.Caution, "SLAT FAIL"],
    [CasMessage.SLAT_AND_FLAP_FAIL]: [MessageLevel.Caution, "SLAT-FLAP FAIL"],
    [CasMessage.SLAT_SLOW_CAUT]: [MessageLevel.Caution, "SLAT SLOW"],
    [CasMessage.FLAP_SLOW_CAUT]: [MessageLevel.Caution, "FLAP SLOW"],
    [CasMessage.SLAT_SLOW_ADV]: [MessageLevel.Advisory, "SLAT SLOW"],
    [CasMessage.FLAP_SLOW_ADV]: [MessageLevel.Advisory, "FLAP SLOW"],
    [CasMessage.SLAT_FAULT]: [MessageLevel.Advisory, "SLAT FAULT"],
    [CasMessage.FLAP_FAULT]: [MessageLevel.Advisory, "FLAP FAULT"],
    [CasMessage.ALTN_FLAP_DPLY]: [MessageLevel.Status, "ALTN FLAP DPLY"],
    [CasMessage.HYD_1_HI_TEMP]: [MessageLevel.Caution, "HYD 1 HI TEMP"],
    [CasMessage.HYD_2_HI_TEMP]: [MessageLevel.Caution, "HYD 2 HI TEMP"],
    [CasMessage.HYD_3_HI_TEMP]: [MessageLevel.Caution, "HYD 3 HI TEMP"],
    [CasMessage.HYD_1_LO_PRESS]: [MessageLevel.Caution, "HYD 1 LO PRESS"],
    [CasMessage.HYD_2_LO_PRESS]: [MessageLevel.Caution, "HYD 2 LO PRESS"],
    [CasMessage.HYD_3_LO_PRESS]: [MessageLevel.Caution, "HYD 3 LO PRESS"],
    [CasMessage.HYD_1_2_LO_PRESS]: [MessageLevel.Caution, "HYD 1-2 LO PRESS"],
    [CasMessage.HYD_2_3_LO_PRESS]: [MessageLevel.Caution, "HYD 2-3 LO PRESS"],
    [CasMessage.HYD_1_3_LO_PRESS]: [MessageLevel.Caution, "HYD 1-3 LO PRESS"],
    [CasMessage.HYD_1_SOV_FAIL]: [MessageLevel.Caution, "HYD 1 SOV FAIL"],
    [CasMessage.HYD_2_SOV_FAIL]: [MessageLevel.Caution, "HYD 2 SOV FAIL"],
    [CasMessage.HYD_EDP_1A_FAIL]: [MessageLevel.Caution, "HYD EDP 1A FAIL"],
    [CasMessage.HYD_PTU_FAIL]: [MessageLevel.Caution, "HYD PTU FAIL"],
    [CasMessage.HYD_EDP_2A_FAIL]: [MessageLevel.Caution, "HYD EDP 2A FAIL"],
    [CasMessage.HYD_PUMP_2B_FAIL]: [MessageLevel.Caution, "HYD PUMP 2B FAIL"],
    [CasMessage.HYD_PUMP_3A_FAIL]: [MessageLevel.Caution, "HYD PUMP 3A FAIL"],
    [CasMessage.HYD_PUMP_3B_FAIL]: [MessageLevel.Caution, "HYD PUMP 3B FAIL"],
    [CasMessage.HYD_RAT_PUMP_FAIL]: [MessageLevel.Caution, "HYD RAT PUMP FAIL"],
    [CasMessage.HYD_1_LO_QTY]: [MessageLevel.Advisory, "HYD 1 LO QTY"],
    [CasMessage.HYD_2_LO_QTY]: [MessageLevel.Advisory, "HYD 2 LO QTY"],
    [CasMessage.HYD_3_LO_QTY]: [MessageLevel.Advisory, "HYD 3 LO QTY"],
    [CasMessage.HYD_1_SOV_CLSD_ADV]: [MessageLevel.Advisory, "HYD 1 SOV CLSD"],
    [CasMessage.HYD_2_SOV_CLSD_ADV]: [MessageLevel.Advisory, "HYD 2 SOV CLSD"],
    [CasMessage.HYDRAULIC_FAULT]: [MessageLevel.Advisory, "HYDRAULIC FAULT"],
    [CasMessage.HYD_1_SOV_CLSD_STAT]: [MessageLevel.Status, "HYD 1 SOV CLSD"],
    [CasMessage.HYD_2_SOV_CLSD_STAT]: [MessageLevel.Status, "HYD 2 SOV CLSD"],
    [CasMessage.HYD_PTU_OFF]: [MessageLevel.Status, "HYD PTU OFF"],
    [CasMessage.HYD_PTU_ON]: [MessageLevel.Status, "HYD PTU ON"],
    [CasMessage.HYD_PUMP_2B_OFF]: [MessageLevel.Status, "HYD PUMP 2B OFF"],
    [CasMessage.HYD_PUMP_2B_ON]: [MessageLevel.Status, "HYD PUMP 2B ON"],
    [CasMessage.HYD_PUMP_3A_OFF]: [MessageLevel.Status, "HYD PUMP 3A OFF"],
    [CasMessage.HYD_PUMP_3A_ON]: [MessageLevel.Status, "HYD PUMP 3A ON"],
    [CasMessage.HYD_PUMP_3B_OFF]: [MessageLevel.Status, "HYD PUMP 3B OFF"],
    [CasMessage.HYD_PUMP_3B_ON]: [MessageLevel.Status, "HYD PUMP 3B ON"],
    [CasMessage.AIR_SYSTEM_FAULT]: [MessageLevel.Advisory, "AIR SYSTEM FAULT"],
    [CasMessage.LEAK_DET_FAULT]: [MessageLevel.Advisory, "LEAK DET FAULT"],
    [CasMessage.PACK_FAULT]: [MessageLevel.Advisory, "PACK FAULT"],
    [CasMessage.EQUIP_BAY_COOL_FAULT]: [MessageLevel.Advisory, "EQUIP BAY COOL FAULT"],
    [CasMessage.WING_A_ICE_FAULT]: [MessageLevel.Advisory, "WING A/ICE FAULT"],
    [CasMessage.PRESSURIZATION_FAULT]: [MessageLevel.Advisory, "PRESSURIZATION FAULT"],
    [CasMessage.KU_BAND_ON]: [MessageLevel.Caution, "KU BAND ON"],
    [CasMessage.CTRL_PANEL_FAULT]: [MessageLevel.Advisory, "CTRL PANEL FAULT"],
    [CasMessage.L_ICE_DET_FAIL]: [MessageLevel.Caution, "L ICE DET FAIL"],
    [CasMessage.R_ICE_DET_FAIL]: [MessageLevel.Caution, "R ICE DET FAIL"],
    [CasMessage.ICE_CAUT]: [MessageLevel.Caution, "ICE"],
    [CasMessage.ICE_ADV]: [MessageLevel.Advisory, "ICE"],
    [CasMessage.EMER_LTS_ON]: [MessageLevel.Status, "EMER LTS ON"],
    [CasMessage.EMER_LTS_OFF]: [MessageLevel.Caution, "EMER LTS OFF"],
    [CasMessage.IRS_1_FAIL]: [MessageLevel.Advisory, "IRS 1 FAIL"],
    [CasMessage.IRS_2_FAIL]: [MessageLevel.Advisory, "IRS 2 FAIL"],
    [CasMessage.IRS_3_FAIL]: [MessageLevel.Advisory, "IRS 3 FAIL"],
    [CasMessage.IRS_SAME_SOURCE]: [MessageLevel.Caution, "IRS SAME SOURCE"],
    [CasMessage.IRS_SET_HEADING]: [MessageLevel.Caution, "IRS SET HEADING"],
    [CasMessage.IRS_1_POWER_FAULT]: [MessageLevel.Advisory, "IRS 1 POWER FAULT"],
    [CasMessage.IRS_2_POWER_FAULT]: [MessageLevel.Advisory, "IRS 2 POWER FAULT"],
    [CasMessage.IRS_3_POWER_FAULT]: [MessageLevel.Advisory, "IRS 3 POWER FAULT"],
    [CasMessage.CREW_OXY_LO_PRESS]: [MessageLevel.Caution, "CREW OXY LO PRESS"],
    [CasMessage.PAX_OXY_DPLY]: [MessageLevel.Status, "PAX OXY DPLY"],
    [CasMessage.OVERWING_DOOR]: [MessageLevel.Caution, "OVERWING DOOR"],
    [CasMessage.WING_SLIDE]: [MessageLevel.Caution, "WING SLIDE"],
    [CasMessage.FWD_DOOR]: [MessageLevel.Caution, "FWD DOOR"],
    [CasMessage.AFT_DOOR]: [MessageLevel.Caution, "AFT DOOR"],
    [CasMessage.DOOR_OPEN]: [MessageLevel.Advisory, "DOOR OPEN"],
    [CasMessage.DOOR_FAULT]: [MessageLevel.Advisory, "DOOR FAULT"],
    [CasMessage.FWD_SLIDE]: [MessageLevel.Caution, "FWD SLIDE"],
    [CasMessage.AFT_SLIDE]: [MessageLevel.Caution, "AFT SLIDE"],
    [CasMessage.DOOR_SLIDE_DISARMED_CAUT]: [MessageLevel.Caution, "DOOR SLIDE DISARMED"],
    [CasMessage.DOOR_SLIDE_DISARMED_ADV]: [MessageLevel.Advisory, "DOOR SLIDE DISARMED"],
    [CasMessage.DOOR_SLIDE_FAULT]: [MessageLevel.Advisory, "DOOR SLIDE FAULT"],
    [CasMessage.TIRE_PRESS_FAULT]: [MessageLevel.Advisory, "TIRE PRESS FAULT"],
    [CasMessage.TIRE_LO_PRESS]: [MessageLevel.Advisory, "TIRE LO PRESS"],
    [CasMessage.NOSE_TIRE_LO_PRESS]: [MessageLevel.Caution, "NOSE TIRE LO PRESS"],
    [CasMessage.L_WING_A_ICE_OVHT]: [MessageLevel.Caution, "L WING A/ICE OVHT"],
    [CasMessage.R_WING_A_ICE_OVHT]: [MessageLevel.Caution, "R WING A/ICE OVHT"],
    [CasMessage.WING_A_ICE_MISCONFIG]: [MessageLevel.Caution, "WING A/ICE MISCONFIG"],
    [CasMessage.L_WING_A_ICE_LO_HEAT]: [MessageLevel.Caution, "L WING A/ICE LO HEAT"],
    [CasMessage.R_WING_A_ICE_LO_HEAT]: [MessageLevel.Caution, "R WING A/ICE LO HEAT"],
    [CasMessage.L_WING_A_ICE_FAIL]: [MessageLevel.Warning, "L WING A/ICE FAIL"],
    [CasMessage.R_WING_A_ICE_FAIL]: [MessageLevel.Warning, "R WING A/ICE FAIL"],
    [CasMessage.WING_A_ICE_FAIL]: [MessageLevel.Caution, "WING A/ICE FAIL"],
    [CasMessage.WING_A_ICE_ON_CAUT]: [MessageLevel.Caution, "WING A/ICE ON"],
    [CasMessage.WING_A_ICE_OFF]: [MessageLevel.Status, "WING A/ICE OFF"],
    [CasMessage.WING_A_ICE_ON_STAT]: [MessageLevel.Status, "WING A/ICE ON"],
    [CasMessage.L_WSHLD_HEAT_FAIL_ON]: [MessageLevel.Advisory, "L WSHLD HEAT FAIL ON"],
    [CasMessage.R_WSHLD_HEAT_FAIL_ON]: [MessageLevel.Advisory, "R WSHLD HEAT FAIL ON"],
    [CasMessage.L_SIDE_WDW_HT_FAIL_ON]: [MessageLevel.Advisory, "L SIDE WDW HT FAIL ON"],
    [CasMessage.R_SIDE_WDW_HT_FAIL_ON]: [MessageLevel.Advisory, "R SIDE WDW HT FAIL ON"],
    [CasMessage.L_WSHLD_HEAT_OFF]: [MessageLevel.Status, "L WSHLD HEAT OFF"],
    [CasMessage.R_WSHLD_HEAT_OFF]: [MessageLevel.Status, "R WSHLD HEAT OFF"],
    [CasMessage.L_SIDE_WDW_HEAT_OFF]: [MessageLevel.Status, "L SIDE WDW HEAT OFF"],
    [CasMessage.R_SIDE_WDW_HEAT_OFF]: [MessageLevel.Status, "R SIDE WDW HEAT OFF"],
    [CasMessage.L_WSHLD_HEAT_FAIL]: [MessageLevel.Caution, "L WSHLD HEAT FAIL"],
    [CasMessage.R_WSHLD_HEAT_FAIL]: [MessageLevel.Caution, "R WSHLD HEAT FAIL"],
    [CasMessage.L_SIDE_WDW_HEAT_FAIL]: [MessageLevel.Caution, "L SIDE WDW HEAT FAIL"],
    [CasMessage.R_SIDE_WDW_HEAT_FAIL]: [MessageLevel.Caution, "R SIDE WDW HEAT FAIL"],
};

export const MESSAGE_LEVEL_COLOR: Record<MessageLevel, string> = {
    [MessageLevel.Status]: "#ffffff",
    [MessageLevel.Advisory]: "#00bfe6",
    [MessageLevel.Caution]: "#ffe300",
    [MessageLevel.Warning]: "#ff0000",
};

export function casMessageLabel(msg: CasMessage): string {
    return CAS_MESSAGE_TEXT[msg][1];
}

/** CasMessage enum member name (e.g. "L_ENG_FIRE") -> its numeric value, or undefined if unknown. */
export function casMessageIndex(name: string): number | undefined {
    const v = (CasMessage as unknown as Record<string, number>)[name];
    return typeof v === "number" ? v : undefined;
}

/** Numeric CasMessage value -> its enum member name, or undefined if out of range. */
export function casMessageName(index: number): string | undefined {
    return (CasMessage as unknown as Record<number, string>)[index];
}

export function casMessageLevel(msg: CasMessage): MessageLevel {
    return CAS_MESSAGE_TEXT[msg][0];
}

export interface CasMessageOption {
    message: CasMessage;
    level: MessageLevel;
    label: string;
}

const LEVEL_ORDER = [MessageLevel.Status, MessageLevel.Advisory, MessageLevel.Caution, MessageLevel.Warning];

export const CAS_MESSAGE_OPTIONS: CasMessageOption[] = (Object.keys(CAS_MESSAGE_TEXT).map(Number) as CasMessage[])
    .map((message) => ({ message, level: CAS_MESSAGE_TEXT[message][0], label: CAS_MESSAGE_TEXT[message][1] }))
    .sort((a, b) => LEVEL_ORDER.indexOf(a.level) - LEVEL_ORDER.indexOf(b.level) || a.label.localeCompare(b.label));
